### ISSUE TITLE
Is there an ETA for the 1.14 release?

### ISSUE THREAD

**Issue by Derpitron** [SilentChaos512/SGear-Basic-Metals#1]
I'm new to data packs, so I'm wondering - can I use the 1.13.2 database release with 1.14 Silent's Gear?

If not, then is there an ETA on the 1.14 release?

**Comment by SilentChaos512** [comment]
I believe the 1.13.2 version still works. I haven't made any changes to the JSON format, but I'll double check everything.

**Comment by SilentChaos512** [comment]
Looks like version 1.1 works in Minecraft 1.14.2, so I updated the release title. Reopen if there are any issues.
