### ISSUE TITLE
Basic metals not appearing?

### ISSUE THREAD

**Issue by chantelw** [SilentChaos512/SGear-Basic-Metals#2]
-Silent Gear: SilentGear-1.14.4-1.4.3+68
-Silent's Gems: SilentGems-1.14.4-3.4.4+77
-Silent Lib: SilentLb-1.14.4-4.4.0+44
-Forge: forge-28.1.26
-Modpack: N/A

Hello i've tried all versions of the datapack and none seem to be working correctly for 1.14.4.  None show up in JEI and can only see them with no textures (or as Barrier) in the crafting table
parts menu.

![20191008125013_1](https://user-images.githubusercontent.com/28073370/66415767-5594ee00-e9ca-11e9-8897-7a5bfef083d2.jpg)

**Comment by SilentChaos512** [comment]
Do you have a mod that adds the required ingots? And are those ingots correctly tagged?

**Comment by chantelw** [comment]
No I do not. I'm such a noob and thought that the datapack added them.
